{% set name = "pedesigner" %}
{% set version = "0.2.0" %}
{% set sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: python

source:
  url: https://github.com/VeredKunik/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python >=3.7

  run:
    - python >=3.7
    - cas-offinder

test:
  imports:
    - pedesigner
  commands:
    - pedesigner --help

about:
  home: https://github.com/VeredKunik/pedesigner
  license: GPL3
  license_family: GPL3
  summary: "A tool for prime-editing guideRNA (pegRNA) design"

extra:
  recipe-maintainers:
    - VeredKunik
